force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>To store Customer&apos;s Home Country</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>To store Customer&apos;s Product</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductInformation__c/ProductInformation__c.object-meta.xml
<CustomObject>
    <description>To store product information</description>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductInformation__c/fields/ATMFee__c.field-meta.xml
<CustomField>
    <fullName>ATMFee__c</fullName>
    <description>To store ATM Fee</description>
    <label>ATM Fee</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/CardReplacementCost__c.field-meta.xml
<CustomField>
    <fullName>CardReplacementCost__c</fullName>
    <description>To store Card Replacement Cost</description>
    <label>Card Replacement Cost</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/CostPerCalendarMonth__c.field-meta.xml
<CustomField>
    <fullName>CostPerCalendarMonth__c</fullName>
    <description>To store Cost per Calendar Month</description>
    <label>Cost per Calendar Month</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>To store country value</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <description>To store the Product name</description>
    <label>Product Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactProductInformationTest.cls
@IsTest
private class ContactProductInformationTest {
    
    @testSetup static void dataSetup() {
        
        // Create test records
        List <Contact> contactList = new List<Contact>();
        
        // create product information
        ProductInformation__c proInfo = new ProductInformation__c(ProductName__c = 'Standard', Country__c = 'DE', CostPerCalendarMonth__c = '€ 0', ATMFee__c = '1.7%', CardReplacementCost__c = '€ 6');
        insert proInfo;
        
        // create contact with valid country and product data
        Contact contact1 = new contact(FirstName ='Test', LastName = 'Contact1', Home_Country__c = 'DE', Product__c = 'Standard', UUID__c = 'vmAAE');
        
        // create contact with no product data
        Contact contact2 = new contact(FirstName ='Test', LastName = 'Contact2', Home_Country__c = 'DE', Product__c = '',UUID__c = 'vmAAB' );
        
        contactList.add(contact1);
        contactList.add(contact2);
        insert contactList;
    }
    
    @isTest static void testgetContactProductInfo() {
        
        Contact contact1 = [SELECT Id, UUID__c FROM Contact where Name = 'Test Contact1' LIMIT 1];
        Contact contact2 = [SELECT Id, UUID__c FROM Contact where Name = 'Test Contact2' LIMIT 1];
        
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Contact/' + contact1.UUID__c;
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        // call the method to test
        List<ContactProductInformation.ContactProductWrapper> conProInfo1 = ContactProductInformation.getContactProductInfo();
        
        // verify results - products information should not be empty for contact1
        system.assert(conProInfo1.size() > 0);
        
        
        // set up a test request
        RestRequest request2 = new RestRequest();
        request2.requestUri = '/services/apexrest/Contact/' + contact2.UUID__c;
        request2.httpMethod = 'GET';
        RestContext.request = request2;
        
        // call the method to test
        List<ContactProductInformation.ContactProductWrapper> conProInfo2 = ContactProductInformation.getContactProductInfo();
        
        // verify results - products information should be empty for contact2
        system.assert(conProInfo2.size() == 0);
    }
}