force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>To store Customer&apos;s Home Country</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>To store Customer&apos;s Product</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductInformation__c/ProductInformation__c.object-meta.xml
<CustomObject>
    <description>To store product information</description>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductInformation__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is used to determine if the prices are active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/ATMFee__c.field-meta.xml
<CustomField>
    <fullName>ATMFee__c</fullName>
    <description>To store ATM Fee</description>
    <label>ATM Fee</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/CardReplacementCost__c.field-meta.xml
<CustomField>
    <fullName>CardReplacementCost__c</fullName>
    <description>To store Card Replacement Cost</description>
    <label>Card Replacement Cost</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/CostPerCalendarMonth__c.field-meta.xml
<CustomField>
    <fullName>CostPerCalendarMonth__c</fullName>
    <description>To store Cost per Calendar Month</description>
    <label>Cost per Calendar Month</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>To store country value</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <description>To store the Product name</description>
    <label>Product Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactProductInformation.cls
/*
*********************************************************
Apex Class Name    : ContactProductInformation
Created Date       : May 10, 2024
Description        : This is class is used to retrive contact and product information
Author             : Vignesh Mahalingam
Modification Log:
Ver   Date         Author                               Modification
1.0   10-05-2021   Vignesh Mahalingam                   Initial Version
*********************************************************
*/

@RestResource(urlMapping='/Contact/*')
global with sharing class ContactProductInformation {
    
    // this method parses UUID from request and returns matching contact and its associated product information
    @HttpGet
    global static List<ContactProductWrapper> getContactProductInfo() {
        
        List<ContactProductWrapper> conProInfo = new List<ContactProductWrapper>();
        
        try{
            
            // get UUID from request
            RestRequest request = RestContext.request; 
            String contactUUID = request.requestURI.substring( request.requestURI.lastIndexOf('/')+1);
            
            // fetch contact using UUID
            List<Contact> conList = [SELECT Id, Name, Product__c,Home_Country__c FROM Contact WHERE UUID__c = :contactUUID WITH SECURITY_ENFORCED LIMIT 1];
            
            if(!conList.isEmpty()){     
                
                // fetch product details using Contact's Home country and Product
                if(String.isNotBlank(conList[0].Product__c) && String.isNotBlank(conList[0].Home_Country__c)){
                   List<ProductInformation__c> productInfoList = [SELECT Id, ProductName__c, Country__c, CostPerCalendarMonth__c, ATMFee__c, CardReplacementCost__c FROM ProductInformation__c WHERE Country__c = :conList[0].Home_Country__c AND ProductName__c = :conList[0].Product__c AND Active__c = TRUE WITH SECURITY_ENFORCED LIMIT 1];
                    
                    if(!productInfoList.isEmpty()){
                        conProInfo.add(new ContactProductWrapper(conList[0],productInfoList[0]));
                    }
                }
            }
        }
        
        catch(Exception e){
            // handle exception and log errors 
        }
        
        return conProInfo;
    }
    
    global class ContactProductWrapper {
        public Contact contactInfo {get; set;}
        public ProductInformation__c productInfo {get; set;}
        
        public ContactProductWrapper(Contact contactInfo, ProductInformation__c productInfo){
            this.contactInfo = contactInfo;
            this.productInfo = productInfo;
        }
    }
}