force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>To store Customer&apos;s Home Country</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>To store Customer&apos;s Product</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductInformation__c/ProductInformation__c.object-meta.xml
<CustomObject>
    <description>To store product information</description>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductInformation__c/fields/ATMFee__c.field-meta.xml
<CustomField>
    <fullName>ATMFee__c</fullName>
    <description>To store ATM Fee</description>
    <label>ATM Fee</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/CardReplacementCost__c.field-meta.xml
<CustomField>
    <fullName>CardReplacementCost__c</fullName>
    <description>To store Card Replacement Cost</description>
    <label>Card Replacement Cost</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/CostPerCalendarMonth__c.field-meta.xml
<CustomField>
    <fullName>CostPerCalendarMonth__c</fullName>
    <description>To store Cost per Calendar Month</description>
    <label>Cost per Calendar Month</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>To store country value</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <description>To store the Product name</description>
    <label>Product Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductInformationControllerTest.cls
@isTest
private class ProductInformationControllerTest {
    
    @testSetup static void dataSetup() {
        
        // create test records
        List <Contact> contactList = new List<Contact>();
        List <Case> caseList = new List<Case>();
        
        // create product information
        ProductInformation__c proInfo = new ProductInformation__c(ProductName__c = 'Standard', Country__c = 'DE', CostPerCalendarMonth__c = '€ 0', ATMFee__c = '1.7%', CardReplacementCost__c = '€ 6');
        insert proInfo;
        
        // create contact with valid country and product data
        Contact contact1 = new contact(FirstName ='Test', LastName = 'Contact1', Home_Country__c = 'DE', Product__c = 'Standard');
        
        // create contact with no product data
        Contact contact2 = new contact(FirstName ='Test', LastName = 'Contact2', Home_Country__c = 'DE', Product__c = '');
        
        contactList.add(contact1);
        contactList.add(contact2);
        insert contactList;
        
        // create cases with contacts
        Case case1 = new Case(ContactId = contact1.Id);
        Case case2 = new Case(ContactId = contact2.Id);
        
        caseList.add(case1);
        caseList.add(case2);
        insert caseList;
    }
    
    @isTest static void testfetchProductInformation() {
        
        Case case1 = [SELECT Id FROM Case WHERE Contact.Name = 'Test Contact1' LIMIT 1];
        Case case2 = [SELECT Id FROM Case WHERE Contact.Name = 'Test Contact2' LIMIT 1];
        
        // method call to get product info
        List <ProductInformation__c> productInfo1 = ProductInformationController.fetchProductInformation(case1.Id);
        List <ProductInformation__c> productInfo2 = ProductInformationController.fetchProductInformation(case2.Id);
        
        // product information should not be empty for case1's contact
        system.assert(productInfo1.size() > 0);
        
        // product information should be empty for case2's contact
        system.assert(productInfo2.size() == 0);
    }
}