force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>To store Customer&apos;s Home Country</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>To store Customer&apos;s Product</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductInformation__c/ProductInformation__c.object-meta.xml
<CustomObject>
    <description>To store product information</description>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductInformation__c/fields/ATMFee__c.field-meta.xml
<CustomField>
    <fullName>ATMFee__c</fullName>
    <description>To store ATM Fee</description>
    <label>ATM Fee</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/CardReplacementCost__c.field-meta.xml
<CustomField>
    <fullName>CardReplacementCost__c</fullName>
    <description>To store Card Replacement Cost</description>
    <label>Card Replacement Cost</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/CostPerCalendarMonth__c.field-meta.xml
<CustomField>
    <fullName>CostPerCalendarMonth__c</fullName>
    <description>To store Cost per Calendar Month</description>
    <label>Cost per Calendar Month</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>To store country value</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductInformation__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <description>To store the Product name</description>
    <label>Product Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductInformationController.cls
/*
*********************************************************
Apex Class Name    : ProductInformationController
Created Date       : May 10, 2024
Description        : This is class is used to retrive product information
Author             : Vignesh Mahalingam
Modification Log:
Ver   Date         Author                               Modification
1.0   10-05-2021   Vignesh Mahalingam                   Initial Version
*********************************************************
*/

public with sharing class ProductInformationController {
    
    // this method receives the case record Id and returns the product information of the contact associated with the case
    @AuraEnabled( cacheable=true )  
    public static List<ProductInformation__c> fetchProductInformation(String caseRecordId) {
        
        List<ProductInformation__c> productInfoList = new List<ProductInformation__c>();
        
        try{
            // get case details using Id
            List<Case> caseList = [SELECT Id, ContactId, Contact.Product__c, Contact.Home_Country__c FROM Case WHERE Id = :caseRecordId WITH SECURITY_ENFORCED];
            
            if(!caseList.isEmpty()){
                if(String.isNotBlank(caseList[0].ContactId) && String.isNotBlank(caseList[0].Contact.Product__c) && String.isNotBlank(caseList[0].Contact.Home_Country__c)){
                    
                    // fetch product information using the Contact's Home country and Product
                    productInfoList = [SELECT Id, ProductName__c, Country__c, CostPerCalendarMonth__c, ATMFee__c, CardReplacementCost__c FROM ProductInformation__c WHERE Country__c = :caseList[0].Contact.Home_Country__c AND ProductName__c = :caseList[0].Contact.Product__c WITH SECURITY_ENFORCED LIMIT 1];
                } 
            }
        }
        
        catch(Exception e){
            // handle exception and log errors 
        }
        
        return productInfoList;
    }
}